# 操作系统
os: linux
# 使用的语言
language: node_js
# 语言版本
node_js:
  - "12"
# 安装依赖的 命令 可以直接写命令 也可以 直接用shell脚本执行
# Node 项目的install和script 但是这个步骤为了更方便看 将步骤写了出来
install:
  - sh deploy/install.sh
  # - npm install
script: 
  - sh deploy/script.sh
  # - npm run build

# before_install：install 阶段之前执行
# before_script：script 阶段之前执行
# after_failure：script 阶段失败时执行
# after_success：script 阶段成功时执行
# before_deploy：deploy 步骤之前执行
# after_deploy：deploy 步骤之后执行
# after_script：script 阶段之后执行

# 完整的生命周期
# before_install
# install
# before_script
# script
# aftersuccess or afterfailure
# [OPTIONAL] before_deploy
# [OPTIONAL] deploy
# [OPTIONAL] after_deploy
# after_script